(function(global){
  'use strict'; const LF=global.LF;
  class AccessibilityController{
    constructor(){this.utterance=null;this.paused=false;this.voices=[];speechSynthesis?.addEventListener?.('voiceschanged',()=>this.refreshVoices());this.refreshVoices();}
    refreshVoices(){this.voices=global.speechSynthesis?.getVoices?.()||[];return this.voices;}
    apply(settings){const a=settings.accessibility||{},root=document.documentElement;root.dataset.theme=settings.appearance?.theme||'dark';root.classList.toggle('high-contrast',!!a.highContrast);root.classList.toggle('reduce-motion',!!a.reduceMotion);root.classList.toggle('dyslexia-friendly',!!a.dyslexiaFriendly);root.classList.toggle('large-targets',!!a.largeTargets);root.style.setProperty('--font-scale',String(a.fontScale||1));root.style.setProperty('--reading-line-height',String(a.lineHeight||1.65));root.style.setProperty('--paragraph-spacing',`${a.paragraphSpacing||1}em`);root.style.setProperty('--reading-width',`${a.textWidth||78}ch`);}
    speak(text,label='text'){if(!('speechSynthesis'in global)){LF.toast('Read aloud is unavailable in this browser.','warning');return;}this.stop(true);const clean=String(text||'').trim();if(!clean){LF.toast('There is no text to read.','warning');return;}const u=new SpeechSynthesisUtterance(clean);const r=LF.state.settings.reading||{};u.rate=Number(r.rate||1);u.pitch=Number(r.pitch||1);const voice=this.voices.find(v=>v.name===r.voice);if(voice)u.voice=voice;u.onstart=()=>LF.events.emit('speech:start',{label});u.onend=()=>{this.utterance=null;this.paused=false;LF.events.emit('speech:end');};u.onerror=e=>{if(e.error!=='canceled')LF.toast(`Read aloud: ${e.error}`,'warning');};this.utterance=u;speechSynthesis.speak(u);}
    pauseResume(){if(!this.utterance)return;if(speechSynthesis.paused){speechSynthesis.resume();this.paused=false;}else{speechSynthesis.pause();this.paused=true;}}
    stop(silent=false){if('speechSynthesis'in global)speechSynthesis.cancel();this.utterance=null;this.paused=false;if(!silent)LF.toast('Read aloud stopped.');}
    installKeyboard(){document.addEventListener('keydown',e=>{if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='k'){e.preventDefault();document.getElementById('globalSearch')?.focus();document.getElementById('globalSearch')?.select();}if((e.ctrlKey||e.metaKey)&&e.shiftKey&&e.key.toLowerCase()==='n'){e.preventDefault();LF.app?.quickCapture?.();}if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='s'){e.preventDefault();LF.editor?.save?.({forceSync:false});}if(e.altKey&&e.key==='1'){e.preventDefault();LF.app?.navigate?.('home');}if(e.altKey&&e.key==='2'){e.preventDefault();LF.app?.navigate?.('manuscript');}if(e.altKey&&e.key==='3'){e.preventDefault();LF.app?.navigate?.('notes');}if(e.key==='Escape'&&document.documentElement.classList.contains('focus-mode'))LF.app?.toggleFocus?.(false);});}
  }
  LF.a11y=new AccessibilityController();
})(window);
