(function(global){
  'use strict';
  const LF=global.LF;
  const esc=v=>LF.escapeHtml(v==null?'':v);
  const ACTIONS=[
    'health','manifest','client.config','auth.register','auth.login','auth.google','auth.logout','auth.me','auth.password.change','auth.password.reset.request','auth.password.reset.complete','auth.sessions.list','auth.sessions.revoke','auth.sessions.revoke.others','auth.recovery.codes.generate','auth.recovery.contacts.list','auth.recovery.contacts.add','auth.recovery.contacts.remove','auth.recovery.contacts.sendcode','auth.recovery.code.login','auth.contact.code.verify','profile.get','profile.update','settings.get','settings.update','projects.create','projects.update','projects.get','projects.list','projects.archive','projects.restore','nodes.save','nodes.get','nodes.list','nodes.move','nodes.delete','nodes.restore','notes.save','notes.quickcapture','notes.get','notes.list','notes.search','notes.delete','notes.restore','notes.recentlydeleted','notes.folders.create','notes.folders.update','notes.folders.list','notes.folders.delete','notes.tags.list','attachments.upload','attachments.list','attachments.delete','imports.register','imports.list','entities.save','entities.get','entities.list','entities.delete','timeline.save','timeline.list','timeline.delete','languages.save','languages.get','languages.list','languages.delete','lexicon.save','lexicon.list','lexicon.delete','plotissues.save','plotissues.list','plotissues.resolve','plotissues.delete','plotissues.scan','search.global','search.saved.save','search.saved.list','search.saved.delete','reading.state.get','reading.state.save','export.project','export.user','backup.create','trash.list','activity.list'
  ];
  const COVERAGE=[
    ['Accounts & password auth','Sign in / register plus account tools','auth.register · auth.login · auth.logout · auth.me'],
    ['Google sign-in','Optional hosted-origin helper / raw action','auth.google'],
    ['Sessions & recovery','Cloud Control dialogs','auth.sessions.* · auth.recovery.* · auth.contact.code.verify'],
    ['Profile & preferences','Cloud Control + Settings','profile.* · settings.*'],
    ['Projects & directories','Projects / Manuscript + Cloud Control','projects.* · nodes.*'],
    ['Notes, folders & tags','Notes & Journal + Cloud Control','notes.*'],
    ['Attachments & imports','Editor attachment tools + import tools','attachments.* · imports.*'],
    ['Characters, world & timeline','Character / World / Timeline workspaces','entities.* · timeline.*'],
    ['Constructed languages','Language Lab','languages.* · lexicon.*'],
    ['Continuity / plot issues','Continuity workspace','plotissues.*'],
    ['Search & saved searches','Global Search + Cloud Control','search.*'],
    ['Read-aloud state','Accessibility + Cloud Control','reading.state.*'],
    ['Exports & backups','Data portability + Cloud Control','export.* · backup.create'],
    ['Trash & audit history','Recently Deleted + Cloud Control','trash.list · activity.list']
  ];

  async function call(action,data={},publicCall=false){return LF.api.request(action,data,publicCall?{token:''}:{});}
  function pretty(x){return JSON.stringify(x,null,2);}
  async function modalJson(title,value){return LF.dialog({title,wide:true,body:`<pre class="backend-json">${esc(pretty(value))}</pre>`,confirmText:'Close'});}
  async function promptFields(title,fields,confirmText='Continue'){
    const body=fields.map(f=>`<label class="field">${esc(f.label)}${f.type==='textarea'?`<textarea id="${f.id}" rows="${f.rows||5}" placeholder="${esc(f.placeholder||'')}">${esc(f.value||'')}</textarea>`:`<input id="${f.id}" type="${f.type||'text'}" value="${esc(f.value||'')}" placeholder="${esc(f.placeholder||'')}">`}</label>`).join('');
    const r=await LF.dialog({title,wide:true,body,confirmText});if(!r)return null;const out={};fields.forEach(f=>out[f.id]=r.root.querySelector('#'+f.id).value);return out;
  }

  const Console={
    async mount(root,app){
      const signed=!!LF.api.token;
      root.innerHTML=`<section class="view-page backend-console"><header class="view-header"><div><p class="eyebrow">Existing backend, fully surfaced</p><h1>Cloud & Account</h1><p>This workspace uses the supplied LiteraryFriend backend contract as-is. The app remains local-first and free; cloud/account features are optional.</p></div><div class="header-actions"><button id="bcHealth" class="button button--secondary" type="button">Check backend</button>${signed?'<button id="bcSync" class="button button--primary" type="button">Sync queue</button>':'<button id="bcSignIn" class="button button--primary" type="button">Sign in / register</button>'}</div></header>
      <div class="backend-grid">
        <section class="panel"><h2>Connection</h2><dl class="detail-list"><div><dt>Endpoint</dt><dd class="break-anywhere">${esc(LF.API_CONFIG.endpoint)}</dd></div><div><dt>Apps Script library</dt><dd class="break-anywhere">${esc(LF.API_CONFIG.libraryUrl)}</dd></div><div><dt>Mode</dt><dd>${signed?'Authenticated cloud + local':'Local-first, cloud ready'}</dd></div><div><dt>Queued writes</dt><dd>${LF.api.queue.length}</dd></div></dl><div id="bcHealthResult" class="backend-status">Not checked this session.</div></section>
        <section class="panel"><h2>Account & recovery</h2>${signed?`<p><strong>${esc(LF.api.user?.displayName||LF.api.user?.username||LF.api.user?.email||'Connected account')}</strong></p><div class="action-list"><button data-bc="profile">Profile</button><button data-bc="password">Change password</button><button data-bc="sessions">Device sessions</button><button data-bc="recovery">Recovery contacts & codes</button><button data-bc="logout">Sign out</button></div>`:`<p class="muted">No backend account is signed in. Local writing does not require one.</p><div class="action-list"><button data-bc="signin">Sign in / register</button><button data-bc="reset">Request password reset</button><button data-bc="resetComplete">Complete password reset</button><button data-bc="recoveryLogin">Use recovery code</button></div>`}</section>
        <section class="panel"><h2>Cloud data tools</h2><div class="action-list"><button data-bc="remoteProjects">Remote projects</button><button data-bc="remoteNotes">Remote notes, folders & tags</button><button data-bc="remoteImports">Imports & attachments</button><button data-bc="cloudSearch">Cloud search & saved searches</button><button data-bc="exports">Exports & backup</button><button data-bc="history">Cloud trash & activity</button><button data-bc="reading">Reading-state storage</button></div></section>
        <section class="panel"><h2>Backend capability coverage</h2><p class="small muted">Every published action is represented by a normal workspace, a Cloud Control tool, or the advanced action runner below.</p><div class="coverage-list">${COVERAGE.map(x=>`<details><summary>${esc(x[0])}</summary><p>${esc(x[1])}</p><code>${esc(x[2])}</code></details>`).join('')}</div></section>
      </div>
      <section class="panel backend-runner"><div class="panel-heading"><h2>Advanced backend action runner</h2><span class="muted small">No new routes are created</span></div><p class="small muted">For exact backend operations not needed in the everyday writing UI. Enter only the <code>data</code> object; authentication is supplied from the current session when required.</p><div class="backend-runner-grid"><label class="field">Action<select id="bcAction">${ACTIONS.map(a=>`<option>${a}</option>`).join('')}</select></label><label class="field field--wide">Data JSON<textarea id="bcData" rows="8">{}</textarea></label></div><div class="button-row"><button id="bcRun" class="button button--secondary" type="button">Run action</button><button id="bcCopyCoverage" class="button button--ghost" type="button">Copy action list</button></div><pre id="bcOutput" class="backend-json" aria-live="polite">Ready.</pre></section></section>`;
      root.querySelector('#bcHealth').onclick=()=>this.health(root);
      root.querySelector('#bcSync')?.addEventListener('click',()=>app.syncNow());
      root.querySelector('#bcSignIn')?.addEventListener('click',()=>app.authDialog().then(()=>app.navigate('cloud')));
      root.querySelectorAll('[data-bc]').forEach(b=>b.onclick=()=>this.action(b.dataset.bc,root,app));
      root.querySelector('#bcRun').onclick=()=>this.runRaw(root);
      root.querySelector('#bcCopyCoverage').onclick=()=>{LF.copyText(ACTIONS.join('\n'));LF.toast('Backend action list copied.','success');};
    },
    async health(root){const box=root.querySelector('#bcHealthResult');box.textContent='Checking…';try{const h=await LF.api.health();box.textContent=`${h.app||'LiteraryFriend'} ${h.version||''} · ${h.configured?'configured':'setup incomplete'} · ${h.storage||'backend online'}`;box.dataset.tone='ok';}catch(e){box.textContent=e.message;box.dataset.tone='error';}},
    async action(name,root,app){
      try{
        if(name==='signin'){await app.authDialog();return app.navigate('cloud');}
        if(name==='logout'){await LF.api.logout();LF.toast('Signed out.','success');return app.navigate('cloud');}
        if(name==='profile'){return modalJson('Cloud profile',await call('profile.get'));}
        if(name==='password'){const v=await promptFields('Change password',[{id:'currentPassword',label:'Current password',type:'password'},{id:'newPassword',label:'New password (10+ characters)',type:'password'}],'Change password');if(v)await modalJson('Password result',await call('auth.password.change',v));return;}
        if(name==='reset'){const v=await promptFields('Request password reset',[{id:'login',label:'Email or username'}],'Send reset code');if(v)await modalJson('Reset request',await call('auth.password.reset.request',v,true));return;}
        if(name==='resetComplete'){const v=await promptFields('Complete password reset',[{id:'login',label:'Email or username'},{id:'code',label:'Verification code'},{id:'newPassword',label:'New password (10+ characters)',type:'password'}],'Reset password');if(v)await modalJson('Password reset',await call('auth.password.reset.complete',v,true));return;}
        if(name==='recoveryLogin'){const v=await promptFields('Recovery-code sign in',[{id:'login',label:'Email or username'},{id:'code',label:'One-time recovery code'}],'Sign in');if(!v)return;const r=await call('auth.recovery.code.login',v,true);if(r.token){LF.api.token=r.token;LF.api.user=r.user||null;LF.api.saveAuth();}await modalJson('Recovery sign-in',r);return app.navigate('cloud');}
        if(name==='sessions'){const r=await call('auth.sessions.list');const sessions=r.sessions||[];const html=`<div class="record-list">${sessions.map(s=>`<div class="record-row"><span class="record-row__main"><strong>${esc(s.deviceName||s.platform||'Session')}</strong><small>${esc(s.lastSeenAt||s.createdAt||'')}</small></span><button data-revoke="${esc(s.id)}" class="button button--danger" type="button">Revoke</button></div>`).join('')||'<p class="muted">No sessions returned.</p>'}</div><div class="button-row"><button id="revokeOthers" class="button button--ghost" type="button">Revoke other sessions</button></div>`;const d=await LF.dialog({title:'Device sessions',wide:true,body:html,confirmText:'Close',onMount:m=>{m.querySelectorAll('[data-revoke]').forEach(b=>b.onclick=async()=>{await call('auth.sessions.revoke',{sessionId:b.dataset.revoke});b.closest('.record-row')?.remove();LF.toast('Session revoked.','success');});m.querySelector('#revokeOthers').onclick=async()=>{await call('auth.sessions.revoke.others');LF.toast('Other sessions revoked.','success');};}});return d;}
        if(name==='recovery'){const [contacts,codesInfo]=await Promise.all([call('auth.recovery.contacts.list'),Promise.resolve(null)]);const list=contacts.contacts||[];const body=`<p>Verified recovery contacts can receive verification codes. Generating a new recovery-code batch invalidates older unused batches.</p><div class="record-list">${list.map(c=>`<div class="record-row"><span class="record-row__main"><strong>${esc(c.label||c.kind)}</strong><small>${esc(c.kind)} · ${esc(c.value)} · ${c.verified?'verified':'unverified'}</small></span><button data-send-contact="${esc(c.id)}">Send code</button>${c.verified?'':`<button data-verify-contact="${esc(c.id)}">Verify</button>`}<button data-remove-contact="${esc(c.id)}" class="danger-text">Remove</button></div>`).join('')||'<p class="muted">No recovery contacts returned.</p>'}</div><div class="button-row"><button id="addRecovery" class="button button--secondary">Add contact</button><button id="genCodes" class="button button--primary">Generate recovery codes</button></div><pre id="recoveryCodesOut" class="backend-json"></pre>`;return LF.dialog({title:'Recovery contacts & codes',wide:true,body,confirmText:'Close',onMount:m=>{m.querySelector('#addRecovery').onclick=async()=>{const v=await promptFields('Add recovery contact',[{id:'kind',label:'Kind (email or phone)',value:'email'},{id:'value',label:'Email address or phone number'},{id:'label',label:'Label',value:'Recovery contact'}],'Add');if(v){await call('auth.recovery.contacts.add',v);LF.toast('Recovery contact added.','success');}};m.querySelector('#genCodes').onclick=async()=>{const r=await call('auth.recovery.codes.generate');m.querySelector('#recoveryCodesOut').textContent=pretty(r.codes||r);};m.querySelectorAll('[data-send-contact]').forEach(b=>b.onclick=()=>call('auth.recovery.contacts.sendcode',{contactId:b.dataset.sendContact}).then(()=>LF.toast('Verification code sent.','success')).catch(e=>LF.toast(e.message,'danger')));m.querySelectorAll('[data-verify-contact]').forEach(b=>b.onclick=async()=>{const v=await promptFields('Verify recovery contact',[{id:'code',label:'Verification code'}],'Verify');if(!v)return;const userId=LF.api.user?.id||'';if(!userId){LF.toast('Sign in again so LiteraryFriend can identify the account.','warning');return;}await call('auth.contact.code.verify',{userId,contactId:b.dataset.verifyContact,code:v.code},true);LF.toast('Recovery contact verified.','success');b.remove();});m.querySelectorAll('[data-remove-contact]').forEach(b=>b.onclick=()=>call('auth.recovery.contacts.remove',{contactId:b.dataset.removeContact}).then(()=>b.closest('.record-row')?.remove()));}});}
        if(!LF.api.token){LF.toast('Sign in to use this cloud tool.','warning');return;}
        if(name==='remoteProjects')return modalJson('Remote projects',await call('projects.list',{includeArchived:true,limit:500}));
        if(name==='remoteNotes'){const p=await app.activeProject(),pid=p?.backendId||'';const [notes,folders,tags]=await Promise.all([call('notes.list',{projectId:pid,limit:500}),call('notes.folders.list',{projectId:pid}),call('notes.tags.list',{projectId:pid})]);return modalJson('Remote notes, folders & tags',{notes,folders,tags});}
        if(name==='remoteImports'){const p=await app.activeProject(),pid=p?.backendId||'';const [imports,attachments]=await Promise.all([call('imports.list',{projectId:pid}),call('attachments.list',{projectId:pid})]);return modalJson('Imports & attachments',{imports,attachments});}
        if(name==='cloudSearch'){const v=await promptFields('Cloud search',[{id:'query',label:'Search query'}],'Search');if(!v)return;const p=await app.activeProject();return modalJson('Cloud search results',await call('search.global',{query:v.query,projectId:p?.backendId||'',limit:100}));}
        if(name==='exports'){const p=await app.activeProject();const body=`<p>Create backend-managed exports or backups using the existing backend routes.</p><div class="action-list"><button id="expProject">Export active project</button><button id="expUser">Export account</button><button id="backupUser">Create backup</button></div><pre id="expOut" class="backend-json"></pre>`;return LF.dialog({title:'Exports & backup',wide:true,body,confirmText:'Close',onMount:m=>{const out=m.querySelector('#expOut');m.querySelector('#expProject').onclick=async()=>out.textContent=pretty(await call('export.project',{projectId:p?.backendId||''}));m.querySelector('#expUser').onclick=async()=>out.textContent=pretty(await call('export.user',{}));m.querySelector('#backupUser').onclick=async()=>out.textContent=pretty(await call('backup.create',{}));}});}
        if(name==='history'){const [trash,activity]=await Promise.all([call('trash.list',{limit:500}),call('activity.list',{limit:200})]);return modalJson('Cloud trash & activity',{trash,activity});}
        if(name==='reading'){const p=await app.activeProject();const v=await promptFields('Reading state',[{id:'targetType',label:'Target type',value:'project'},{id:'targetId',label:'Target ID',value:p?.backendId||''},{id:'position',label:'Position',value:'0'},{id:'speed',label:'Speech speed',value:String(LF.state.settings.reading?.rate||1)}],'Save reading state');if(!v)return;const saved=await call('reading.state.save',{projectId:p?.backendId||'',targetType:v.targetType,targetId:v.targetId,position:Number(v.position||0),speed:Number(v.speed||1),voice:LF.state.settings.reading?.voice||'',settings:{}});return modalJson('Reading state saved',saved);}
      }catch(e){LF.toast(e.message,'danger');}
    },
    async runRaw(root){const action=root.querySelector('#bcAction').value,out=root.querySelector('#bcOutput');let data={};try{data=JSON.parse(root.querySelector('#bcData').value||'{}');}catch(e){out.textContent='Data JSON is invalid: '+e.message;return;}out.textContent='Running…';try{const publicCall=['health','manifest','client.config','auth.register','auth.login','auth.google','auth.password.reset.request','auth.password.reset.complete','auth.recovery.code.login','auth.contact.code.verify'].includes(action);const r=await call(action,data,publicCall);out.textContent=pretty(r);}catch(e){out.textContent=`ERROR: ${e.message}`;}
    }
  };
  global.LFBackendConsole=Console;
})(window);
