(function(global){
  'use strict';
  const LF=global.LF;

  class EditorController{
    constructor(){this.record=null;this.el=null;this.titleEl=null;this.statsEl=null;this.saveTimer=null;this.dirty=false;this.lastSnapshotWords=0;this.speechRec=null;this.mediaRecorder=null;this.mediaChunks=[];this.boundInput=LF.debounce(()=>this.onInput(),250);}
    async mount(record,{container=document.getElementById('viewRoot'),showMeta=true}={}){
      this.destroy();this.record=record;
      const noteFolders=record.type==='note'?await LF.store.list('noteFolder',{projectId:record.projectId||undefined,sort:'title-asc'}):[];
      container.innerHTML=`<section class="editor-shell" aria-label="Document editor">
        <header class="editor-header">
          <div class="editor-title-row"><input id="editorTitle" class="editor-title" value="${LF.escapeAttr(record.title||'Untitled')}" aria-label="Document title"><div class="editor-status" id="editorStatus">Saved locally</div></div>
          <div class="editor-meta-row">${showMeta?`<label>Tags <input id="editorTags" value="${LF.escapeAttr((record.tags||[]).join(', '))}" placeholder="character, chapter, research"></label>`:''}${record.type==='note'?`<label class="inline-select">Folder <select id="editorFolder"><option value="">No folder</option>${noteFolders.map(f=>`<option value="${f.id}" ${f.id===record.folderId?'selected':''}>${LF.escapeHtml(f.title)}</option>`).join('')}</select></label>`:''}<label class="inline-select">Status <select id="editorDocStatus"><option value="draft">Draft</option><option value="revising">Revising</option><option value="complete">Complete</option><option value="archived">Archived</option></select></label><button id="pinDocBtn" class="icon-button" type="button" aria-pressed="${!!record.pinned}" title="Pin">${record.pinned?'★':'☆'}</button><button id="inspectorBtn" class="button button--ghost" type="button">Inspector</button></div>
        </header>
        <div class="editor-toolbar" role="toolbar" aria-label="Formatting and writing tools">
          <div class="toolbar-group"><button data-cmd="undo" type="button" title="Undo">↶</button><button data-cmd="redo" type="button" title="Redo">↷</button></div>
          <div class="toolbar-group"><button data-cmd="bold" type="button"><strong>B</strong></button><button data-cmd="italic" type="button"><em>I</em></button><button data-cmd="underline" type="button"><u>U</u></button><button data-block="h2" type="button">H2</button><button data-block="blockquote" type="button">❝</button></div>
          <div class="toolbar-group"><button data-cmd="insertUnorderedList" type="button" title="Bulleted list">• List</button><button data-cmd="insertOrderedList" type="button" title="Numbered list">1. List</button><button id="checklistBtn" type="button" title="Checklist">☑ List</button><button id="tableBtn" type="button" title="Insert table">▦</button></div>
          <div class="toolbar-group"><button id="linkBtn" type="button" title="Insert link">🔗</button><button id="wikiLinkBtn" type="button" title="Link another LiteraryFriend document">[[]]</button><button id="attachmentBtn" type="button" title="Attach file">📎</button><button id="scanBtn" type="button" title="Capture document or image">▣ Scan</button><button id="drawBtn" type="button" title="Sketch">✎ Sketch</button><button id="audioBtn" type="button" title="Record audio">● Audio</button><button id="dictateBtn" type="button" title="Dictate text">🎙 Dictate</button></div>
          <div class="toolbar-group"><button id="snapshotBtn" type="button" title="Save version snapshot">◫ Version</button><button id="findBtn" type="button" title="Find and replace">⌕ Replace</button><button id="calcBtn" type="button" title="Calculate selected expression">= Calc</button><button id="readBtn" type="button" title="Read aloud">▶ Read</button></div>
        </div>
        <div class="writing-surface-wrap"><article id="richEditor" class="rich-editor" contenteditable="true" role="textbox" aria-multiline="true" spellcheck="${LF.state.settings.editor.spellcheck?'true':'false'}" data-placeholder="Start writing…">${record._unlockedContent!==undefined?record._unlockedContent:(record.locked?'':(record.content||''))}</article></div>
        <footer class="editor-footer"><div id="editorStats" class="editor-stats" aria-live="polite"></div><div class="editor-footer__actions"><button id="lockBtn" class="button button--ghost" type="button">${record.locked?'🔒 Locked':'🔓 Lock'}</button><button id="exportDocBtn" class="button button--ghost" type="button">Export</button><button id="printDocBtn" class="button button--ghost" type="button">Print</button><button id="saveDocBtn" class="button button--primary" type="button">Save</button></div></footer>
      </section>`;
      this.el=container.querySelector('#richEditor');this.titleEl=container.querySelector('#editorTitle');this.tagsEl=container.querySelector('#editorTags');this.statusEl=container.querySelector('#editorStatus');this.statsEl=container.querySelector('#editorStats');container.querySelector('#editorDocStatus').value=record.status||'draft';
      this.bind(container);await this.hydrateAttachments();this.updateStats();
      if(record.locked&&!record._unlockedContent) await this.promptUnlock();
      requestAnimationFrame(()=>this.el?.focus());
      LF.events.emit('editor:mounted',record);
    }
    bind(container){
      this.el.addEventListener('input',()=>this.boundInput());this.titleEl.addEventListener('input',()=>this.boundInput());this.tagsEl?.addEventListener('input',()=>this.boundInput());container.querySelector('#editorDocStatus').addEventListener('change',()=>this.onInput());container.querySelector('#editorFolder')?.addEventListener('change',()=>this.onInput());
      container.querySelectorAll('[data-cmd]').forEach(b=>b.addEventListener('click',()=>{this.el.focus();document.execCommand(b.dataset.cmd,false,null);this.onInput();}));
      container.querySelectorAll('[data-block]').forEach(b=>b.addEventListener('click',()=>{this.el.focus();document.execCommand('formatBlock',false,b.dataset.block);this.onInput();}));
      container.querySelector('#checklistBtn').onclick=()=>this.insertChecklist();container.querySelector('#tableBtn').onclick=()=>this.insertTable();container.querySelector('#linkBtn').onclick=()=>this.insertLink();container.querySelector('#wikiLinkBtn').onclick=()=>this.insertWikiLink();container.querySelector('#attachmentBtn').onclick=()=>document.getElementById('attachmentInput').click();container.querySelector('#scanBtn').onclick=()=>document.getElementById('scanInput').click();container.querySelector('#drawBtn').onclick=()=>this.openSketch();container.querySelector('#audioBtn').onclick=e=>this.toggleAudio(e.currentTarget);container.querySelector('#dictateBtn').onclick=e=>this.toggleDictation(e.currentTarget);container.querySelector('#snapshotBtn').onclick=()=>this.snapshot();container.querySelector('#findBtn').onclick=()=>this.findReplace();container.querySelector('#calcBtn').onclick=()=>this.calculateSelection();container.querySelector('#readBtn').onclick=()=>LF.a11y?.speak?.(LF.stripHtml(this.el.innerHTML),this.record.title);container.querySelector('#saveDocBtn').onclick=()=>this.save({forceSync:true});container.querySelector('#pinDocBtn').onclick=async e=>{this.record.pinned=!this.record.pinned;e.currentTarget.textContent=this.record.pinned?'★':'☆';e.currentTarget.setAttribute('aria-pressed',String(this.record.pinned));await this.save();};container.querySelector('#inspectorBtn').onclick=()=>LF.app.showInspector(this.record);container.querySelector('#lockBtn').onclick=()=>this.toggleLock();container.querySelector('#exportDocBtn').onclick=()=>this.exportDocument();container.querySelector('#printDocBtn').onclick=()=>window.print();
      document.getElementById('attachmentInput').onchange=e=>this.attachFiles([...e.target.files]);document.getElementById('scanInput').onchange=e=>this.attachFiles([...e.target.files],{scan:true});
      this.el.addEventListener('paste',e=>this.cleanPaste(e));this.el.addEventListener('drop',e=>this.dropFiles(e));
    }
    cleanPaste(e){const html=e.clipboardData?.getData('text/html'),text=e.clipboardData?.getData('text/plain');if(!html)return; e.preventDefault();const box=document.createElement('div');box.innerHTML=html;box.querySelectorAll('script,style,iframe,object,embed,form,input,button,meta,link').forEach(x=>x.remove());box.querySelectorAll('*').forEach(x=>{[...x.attributes].forEach(a=>{if(/^on/i.test(a.name)||a.name==='style'||a.name==='class')x.removeAttribute(a.name);});});document.execCommand('insertHTML',false,box.innerHTML||LF.escapeHtml(text));}
    dropFiles(e){if(!e.dataTransfer?.files?.length)return;e.preventDefault();this.attachFiles([...e.dataTransfer.files]);}
    onInput(){this.dirty=true;this.status('Unsaved changes');this.updateStats();const secs=LF.state.settings.editor.autosaveSeconds||2;if(LF.state.settings.editor.autosave){clearTimeout(this.saveTimer);this.saveTimer=setTimeout(()=>this.save(),secs*1000);}}
    status(text,tone='neutral'){if(this.statusEl){this.statusEl.textContent=text;this.statusEl.dataset.tone=tone;}}
    currentContent(){return this.el?.innerHTML||'';}
    updateStats(){if(!this.statsEl)return;const s=LF.writer.stats(this.currentContent());const goal=Number(this.record?.wordGoal||LF.state.settings.editor.sessionGoal||0);const progress=goal?Math.min(100,Math.round(s.words/goal*100)):0;this.statsEl.innerHTML=`<span>${s.words.toLocaleString()} words</span><span>${s.characters.toLocaleString()} characters</span><span>${s.readingMinutes} min read</span>${goal?`<span>${progress}% of ${goal.toLocaleString()} goal</span>`:''}`;}
    async save({forceSync=false}={}){if(!this.record||!this.el)return;clearTimeout(this.saveTimer);const content=this.currentContent(),title=this.titleEl.value.trim()||'Untitled',tags=LF.parseTags(this.tagsEl?.value||this.record.tags||[]),status=document.querySelector('#editorDocStatus')?.value||this.record.status||'draft';let patch={...this.record,title,tags,status,folderId:document.querySelector('#editorFolder')?.value??this.record.folderId??''};if(this.record.locked&&this.record._unlockPassword){patch.encrypted=await LF.security.encrypt(content,this.record._unlockPassword);patch.content='';patch._unlockedContent=content;}else patch.content=content;this.record=await LF.store.put(patch);this.dirty=false;this.status('Saved locally','success');LF.events.emit('editor:saved',this.record);if((forceSync||LF.state.settings.privacy.backendEnabled)&&LF.api.token){try{this.status('Syncing…');this.record=await LF.api.pushRecord(this.record);this.status('Saved & synced','success');}catch(err){this.status('Saved locally · sync queued','warning');}}return this.record;}
    insertChecklist(){this.el.focus();document.execCommand('insertHTML',false,'<ul class="checklist"><li><label><input type="checkbox"> <span>Checklist item</span></label></li></ul><p><br></p>');this.onInput();}
    insertTable(){this.el.focus();document.execCommand('insertHTML',false,'<table><thead><tr><th>Heading</th><th>Heading</th></tr></thead><tbody><tr><td>Cell</td><td>Cell</td></tr><tr><td>Cell</td><td>Cell</td></tr></tbody></table><p><br></p>');this.onInput();}
    async insertLink(){const selection=window.getSelection()?.toString()||'';const result=await LF.dialog({title:'Insert link',body:`<label class="field">Link text<input id="linkText" value="${LF.escapeAttr(selection)}"></label><label class="field">URL<input id="linkUrl" type="url" placeholder="https://"></label>`,confirmText:'Insert'});if(!result)return;const text=result.root.querySelector('#linkText').value.trim()||'link',url=result.root.querySelector('#linkUrl').value.trim();if(!url)return;this.el.focus();document.execCommand('insertHTML',false,`<a href="${LF.escapeAttr(url)}" target="_blank" rel="noopener">${LF.escapeHtml(text)}</a>`);this.onInput();}
    async insertWikiLink(){const docs=[...(await LF.store.list('document',{projectId:this.record.projectId,sort:'title-asc'})),...(await LF.store.list('note',{projectId:this.record.projectId,sort:'title-asc'}))].filter(x=>x.id!==this.record.id);const body=`<label class="field">Document<select id="wikiDoc">${docs.map(d=>`<option value="${LF.escapeAttr(d.title)}">${LF.escapeHtml(d.title)}</option>`).join('')}</select></label>`;const result=await LF.dialog({title:'Link LiteraryFriend document',body,confirmText:'Insert link'});if(!result)return;const title=result.root.querySelector('#wikiDoc').value;this.el.focus();document.execCommand('insertText',false,`[[${title}]]`);this.onInput();}
    async attachFiles(files,{scan=false}={}){for(const file of files){if(!file)continue;const blob=await LF.store.putBlob({ownerId:this.record.id,projectId:this.record.projectId||'',name:file.name||`scan-${Date.now()}.jpg`,mimeType:file.type||'application/octet-stream',blob:file,metadata:{scan}});const rec=await LF.store.put({type:'attachment',id:blob.id,blobId:blob.id,ownerId:this.record.id,ownerType:this.record.type,projectId:this.record.projectId||'',name:blob.name,mimeType:blob.mimeType,size:blob.size,scan});if(/^image\//.test(blob.mimeType)){const url=URL.createObjectURL(file);this.el.focus();document.execCommand('insertHTML',false,`<figure data-attachment-id="${rec.id}"><img src="${url}" alt="${LF.escapeAttr(scan?'Scanned image':file.name)}"><figcaption>${LF.escapeHtml(file.name)}</figcaption></figure><p><br></p>`);}else{this.el.focus();document.execCommand('insertHTML',false,`<p class="attachment-chip" data-attachment-id="${rec.id}">📎 ${LF.escapeHtml(file.name)} <small>${Math.ceil(file.size/1024)} KB</small></p>`);}this.onInput();}document.getElementById('attachmentInput').value='';document.getElementById('scanInput').value='';}
    async hydrateAttachments(){if(!this.el)return;for(const fig of this.el.querySelectorAll('[data-attachment-id]')){const id=fig.dataset.attachmentId,img=fig.querySelector('img');if(!img)continue;const b=await LF.store.getBlob(id);if(b?.blob){const old=img.dataset.objectUrl;if(old)URL.revokeObjectURL(old);const url=URL.createObjectURL(b.blob);img.src=url;img.dataset.objectUrl=url;}}}
    async openSketch(){const result=await LF.dialog({title:'Sketch',wide:true,body:'<div class="sketch-tools"><label>Width <input id="penWidth" type="range" min="1" max="24" value="3"></label><button id="clearSketch" class="button button--ghost" type="button">Clear</button></div><canvas id="sketchCanvas" width="1000" height="600" aria-label="Drawing canvas"></canvas>',confirmText:'Insert sketch',onMount:root=>setupCanvas(root)});if(!result)return;const canvas=result.root.querySelector('#sketchCanvas');const blob=await new Promise(r=>canvas.toBlob(r,'image/png'));const file=new File([blob],`sketch-${Date.now()}.png`,{type:'image/png'});await this.attachFiles([file]);}
    async toggleAudio(button){if(this.mediaRecorder?.state==='recording'){this.mediaRecorder.stop();button.textContent='● Audio';return;}if(!navigator.mediaDevices?.getUserMedia){LF.toast('Audio recording is not supported in this browser.','warning');return;}try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});this.mediaChunks=[];this.mediaRecorder=new MediaRecorder(stream);this.mediaRecorder.ondataavailable=e=>{if(e.data.size)this.mediaChunks.push(e.data);};this.mediaRecorder.onstop=async()=>{stream.getTracks().forEach(t=>t.stop());const blob=new Blob(this.mediaChunks,{type:this.mediaRecorder.mimeType||'audio/webm'});const file=new File([blob],`recording-${Date.now()}.webm`,{type:blob.type});await this.attachFiles([file]);LF.toast('Audio recording attached.','success');};this.mediaRecorder.start();button.textContent='■ Stop';LF.toast('Recording audio…');}catch(err){LF.toast(`Microphone unavailable: ${err.message}`,'warning');}}
    toggleDictation(button){const Recognition=window.SpeechRecognition||window.webkitSpeechRecognition;if(!Recognition){LF.toast('Browser speech recognition is unavailable.','warning');return;}if(this.speechRec){this.speechRec.stop();this.speechRec=null;button.textContent='🎙 Dictate';return;}const rec=new Recognition();rec.continuous=true;rec.interimResults=true;rec.lang=document.documentElement.lang||'en-US';let final='';rec.onresult=e=>{let interim='';for(let i=e.resultIndex;i<e.results.length;i++){const t=e.results[i][0].transcript;if(e.results[i].isFinal)final+=t+' ';else interim+=t;}button.title=`Dictating: ${interim||final.slice(-50)}`;if(final){this.el.focus();document.execCommand('insertText',false,final);final='';this.onInput();}};rec.onend=()=>{this.speechRec=null;button.textContent='🎙 Dictate';};rec.onerror=e=>LF.toast(`Dictation: ${e.error}`,'warning');this.speechRec=rec;rec.start();button.textContent='■ Stop dictation';}
    async snapshot(){await this.save();const snap=await LF.store.put({type:'snapshot',projectId:this.record.projectId||'',ownerType:this.record.type,ownerId:this.record.id,title:this.record.title,content:this.record._unlockedContent??this.record.content??'',tags:this.record.tags||[],snapshotAt:LF.now()});LF.toast(`Version saved: ${LF.formatDate(snap.snapshotAt,{hour:'numeric',minute:'2-digit',month:'short',day:'numeric'})}`,'success');}
    async findReplace(){const result=await LF.dialog({title:'Find and replace',body:'<label class="field">Find<input id="findText"></label><label class="field">Replace with<input id="replaceText"></label><div class="check-grid"><label><input id="findCase" type="checkbox"> Match case</label><label><input id="findWhole" type="checkbox"> Whole word</label></div>',confirmText:'Replace all'});if(!result)return;const find=result.root.querySelector('#findText').value,replacement=result.root.querySelector('#replaceText').value;const preview=LF.writer.findReplacePreview(this.el.innerHTML,find,replacement,{caseSensitive:result.root.querySelector('#findCase').checked,wholeWord:result.root.querySelector('#findWhole').checked});this.el.innerHTML=preview.text;this.onInput();LF.toast(`${preview.count} replacement${preview.count===1?'':'s'} made.`,'success');}
    calculateSelection(){const text=window.getSelection()?.toString().trim();if(!text){LF.toast('Select a simple arithmetic expression first.','warning');return;}if(!/^[0-9+\-*/().%\s]+$/.test(text)){LF.toast('Only simple arithmetic can be calculated locally.','warning');return;}try{const value=Function(`"use strict";return (${text.replace(/%/g,'/100')})`)();this.el.focus();document.execCommand('insertText',false,`${text} = ${value}`);this.onInput();}catch(_){LF.toast('That expression could not be calculated.','warning');}}
    async toggleLock(){if(!LF.security.supported){LF.toast('Web encryption is not available in this browser.','warning');return;}if(this.record.locked){if(!this.record._unlockPassword){await this.promptUnlock();return;}const ok=await LF.confirm('Remove encryption from this note body?','Unlock note');if(!ok)return;this.record={...this.record,locked:false,encrypted:null,content:this.currentContent()};delete this.record._unlockPassword;delete this.record._unlockedContent;await LF.store.put(this.record);LF.app.openRecord(this.record);return;}const result=await LF.dialog({title:'Lock note body',body:'<p>The body will be encrypted locally with AES-GCM. LiteraryFriend cannot recover a forgotten password.</p><label class="field">Password<input id="lockPass" type="password" autocomplete="new-password"></label><label class="field">Confirm password<input id="lockPass2" type="password" autocomplete="new-password"></label>',confirmText:'Encrypt & lock'});if(!result)return;const p=result.root.querySelector('#lockPass').value,p2=result.root.querySelector('#lockPass2').value;if(p.length<8){LF.toast('Use at least 8 characters.','warning');return;}if(p!==p2){LF.toast('Passwords do not match.','warning');return;}const encrypted=await LF.security.encrypt(this.currentContent(),p);this.record=await LF.store.put({...this.record,locked:true,encrypted,content:''});this.record._unlockPassword=p;this.record._unlockedContent=this.currentContent();LF.toast('Note body encrypted.','success');LF.app.openRecord(this.record);}
    async promptUnlock(){if(!this.record?.locked)return;const result=await LF.dialog({title:'Unlock note',body:'<label class="field">Password<input id="unlockPass" type="password" autocomplete="current-password"></label>',confirmText:'Unlock'});if(!result){this.el.innerHTML='<p class="locked-placeholder">🔒 This note body is encrypted.</p>';this.el.setAttribute('contenteditable','false');return;}try{const p=result.root.querySelector('#unlockPass').value;const content=await LF.security.decrypt(this.record.encrypted,p);this.record._unlockPassword=p;this.record._unlockedContent=content;this.el.setAttribute('contenteditable','true');this.el.innerHTML=content;this.updateStats();}catch(err){LF.toast(err.message,'danger');this.el.innerHTML='<p class="locked-placeholder">🔒 This note body is encrypted.</p>';this.el.setAttribute('contenteditable','false');}}
    exportDocument(){const md=LF.writer.exportMarkdown({...this.record,content:this.currentContent()});LF.download(`${LF.slug(this.record.title)}.md`,md,'text/markdown;charset=utf-8');}
    async versions(){return LF.store.list('snapshot',{projectId:this.record.projectId,filter:s=>s.ownerId===this.record.id});}
    destroy(){clearTimeout(this.saveTimer);if(this.dirty)this.save().catch(()=>{});if(this.speechRec)try{this.speechRec.stop();}catch(_){}if(this.mediaRecorder?.state==='recording')try{this.mediaRecorder.stop();}catch(_){}this.el=null;this.record=null;this.dirty=false;}
  }

  function setupCanvas(root){const c=root.querySelector('#sketchCanvas'),ctx=c.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);ctx.strokeStyle='#001010';ctx.lineCap='round';let drawing=false,last=null;const point=e=>{const r=c.getBoundingClientRect();return{x:(e.clientX-r.left)*(c.width/r.width),y:(e.clientY-r.top)*(c.height/r.height)}};c.onpointerdown=e=>{drawing=true;last=point(e);c.setPointerCapture(e.pointerId)};c.onpointermove=e=>{if(!drawing)return;const p=point(e);ctx.lineWidth=Number(root.querySelector('#penWidth').value);ctx.beginPath();ctx.moveTo(last.x,last.y);ctx.lineTo(p.x,p.y);ctx.stroke();last=p;};c.onpointerup=()=>drawing=false;c.onpointercancel=()=>drawing=false;root.querySelector('#clearSketch').onclick=()=>{ctx.fillStyle='#fff';ctx.fillRect(0,0,c.width,c.height);};}

  LF.editor=new EditorController();
})(window);
