(function(global){
  'use strict';
  const LF=global.LF;if(!LF)return;
  const CORE_MEANINGS=['I','you','we','they','person','child','parent','friend','stranger','name','home','city','village','road','river','sea','mountain','forest','sky','sun','moon','star','fire','water','earth','air','light','dark','day','night','time','year','past','future','life','death','love','fear','hope','anger','joy','truth','lie','yes','no','good','bad','big','small','old','new','one','two','three','many','eat','drink','sleep','wake','go','come','see','hear','speak','know','think','want','give','take','make','break','fight','help','rule','magic','god','spirit','book','story','word','language','king','queen','leader','war','peace','blood','heart','hand','eye','door','stone','tree','animal','bird','horse','ship'];
  function hash(s){let h=2166136261;for(const c of String(s)){h^=c.charCodeAt(0);h=Math.imul(h,16777619);}return h>>>0;}
  function rng(seed){let x=hash(seed)||1;return()=>((x=Math.imul(1664525,x)+1013904223>>>0)/4294967296);}
  function pick(r,a){return a[Math.floor(r()*a.length)];}
  function makeWord(r,profile){const onset=profile.onsets||['k','t','m','n','s','l','r','v','f','h','sh','th','d','b','g'],vowels=profile.vowels||['a','e','i','o','u'],codas=profile.codas||['','n','s','r','l','m','k','t'];const syl=1+Math.floor(r()*3);let w='';for(let i=0;i<syl;i++)w+=pick(r,onset)+pick(r,vowels)+(r()<.58?pick(r,codas):'');return w.replace(/([a-z])\1\1+/g,'$1$1');}
  LF.story={
    async formatChapters(projectId,{style='chapter-title',pageBreak=true}={}){const docs=(await LF.store.list('document',{projectId,sort:'order'})).filter(d=>d.docType==='chapter');let n=0;for(const d of docs){n++;const box=document.createElement('div');box.innerHTML=d.content||'';const first=box.querySelector('h1.chapter-title');if(first)first.remove();const label=style==='number-title'?`${n}. ${d.title}`:style==='title-only'?d.title:`Chapter ${n}${d.title&&d.title.toLowerCase()!==`chapter ${n}`?` — ${d.title.replace(/^chapter\s+\d+\s*[-—:]?\s*/i,'')}`:''}`;box.insertAdjacentHTML('afterbegin',`<h1 class="chapter-title">${LF.escapeHtml(label)}</h1>${pageBreak?'<hr class="chapter-page-break" aria-hidden="true">':''}`);await LF.store.put({...d,content:box.innerHTML,chapterNumber:n,metadata:{...(d.metadata||{}),chapterFormat:{style,pageBreak}}});}return docs.length;},
    async scanProject(projectId){const docs=await LF.store.list('document',{projectId,sort:'order'}),entities=await LF.store.list('entity',{projectId}),timeline=await LF.store.list('timeline',{projectId});const findings=[];for(const d of docs){const text=LF.stripHtml(d.content||'');for(const m of text.matchAll(/\b(?:TODO|FIXME|TK|TBD|CHECK|RESEARCH)\b[^.!?\n]{0,140}/gi)){findings.push({issueType:'placeholder',severity:'medium',title:`Unresolved draft marker in ${d.title}`,description:'A drafting marker remains in the manuscript.',documentId:d.id,excerpt:m[0],suggestedFix:'',tags:['auto-scan']});}if(!text.trim())findings.push({issueType:'plot hole',severity:'low',title:`Empty manuscript document: ${d.title}`,description:'An empty chapter or scene can create a missing story beat if it is expected in draft order.',documentId:d.id,excerpt:'',suggestedFix:'',tags:['auto-scan']});}
      const seenTitles=new Map();for(const d of docs.filter(x=>x.docType==='chapter')){const k=d.title.toLowerCase().replace(/\s+/g,' ').trim();if(seenTitles.has(k))findings.push({issueType:'continuity',severity:'medium',title:`Duplicate chapter title: ${d.title}`,description:`The title is also used by ${seenTitles.get(k).title}.`,documentId:d.id,excerpt:d.title,suggestedFix:`${d.title} (revised title)`,tags:['auto-scan']});else seenTitles.set(k,d);}
      const aliasOwner=new Map();for(const e of entities){for(const n of [e.name,...(e.aliases||[])].filter(Boolean)){const k=n.toLowerCase();if(aliasOwner.has(k)&&aliasOwner.get(k)!==e.name)findings.push({issueType:'character',severity:'high',title:`Shared name or alias: ${n}`,description:`${aliasOwner.get(k)} and ${e.name} use the same searchable name or alias.`,excerpt:n,suggestedFix:'',tags:['auto-scan']});else aliasOwner.set(k,e.name);}}
      const base=LF.writer.continuityScan({documents:docs,entities,timeline});for(const f of base)if(!findings.some(x=>x.title===f.title))findings.push({...f,tags:[...(f.tags||[]),'auto-scan']});return findings.slice(0,150);},
    async applyIssueFix(issue){if(!issue?.documentId)throw new Error('This issue is not linked to a manuscript document.');const d=await LF.store.get('document',issue.documentId);if(!d)throw new Error('Linked manuscript document was not found.');if(!issue.excerpt)throw new Error('Add an exact excerpt to the issue before applying a fix.');if(issue.suggestedFix==null||issue.suggestedFix==='')throw new Error('Add a suggested replacement before applying a fix.');const src=d.content||'';const plain=LF.stripHtml(src);if(!plain.includes(issue.excerpt))throw new Error('The saved excerpt no longer matches the document. Open the issue and update it first.');const box=document.createElement('div');box.innerHTML=src;const walker=document.createTreeWalker(box,NodeFilter.SHOW_TEXT);let node,done=false;while((node=walker.nextNode())){const i=node.nodeValue.indexOf(issue.excerpt);if(i>=0){node.nodeValue=node.nodeValue.slice(0,i)+issue.suggestedFix+node.nodeValue.slice(i+issue.excerpt.length);done=true;break;}}if(!done)throw new Error('The excerpt crosses formatting boundaries and cannot be replaced automatically.');await LF.store.put({...d,content:box.innerHTML});await LF.store.put({...issue,status:'resolved',resolvedAt:LF.now()});return d;},
    async highlightIssue(app,issue){if(!issue?.documentId)throw new Error('Link this issue to a manuscript document first.');const d=await LF.store.get('document',issue.documentId);if(!d)throw new Error('Linked document was not found.');await app.openRecord(d);if(!issue.excerpt||!LF.editor?.el)return;const el=LF.editor.el;const walker=document.createTreeWalker(el,NodeFilter.SHOW_TEXT);let node;while((node=walker.nextNode())){const i=node.nodeValue.indexOf(issue.excerpt);if(i>=0){const range=document.createRange();range.setStart(node,i);range.setEnd(node,i+issue.excerpt.length);const mark=document.createElement('mark');mark.className='continuity-highlight';mark.title=issue.title;try{range.surroundContents(mark);mark.scrollIntoView({behavior:'smooth',block:'center'});LF.toast('Plot issue highlighted in the editor.','success');}catch(_){LF.toast('The issue location is visible, but complex formatting prevented an inline highlight.','warning');}break;}}},
    buildLanguage({name='Unnamed language',wordOrder='SOV',morphology='agglutinative',sound='balanced',seed=''}){const r=rng(`${name}|${wordOrder}|${morphology}|${sound}|${seed}`);const profiles={soft:{onsets:['m','n','l','r','v','f','s','h','y','w'],vowels:['a','e','i','o','u','ae','ia'],codas:['','n','l','r','s']},hard:{onsets:['k','g','t','d','b','p','kr','gr','sk','dr','z'],vowels:['a','o','u','e'],codas:['k','t','r','n','g','s']},balanced:{}};const p=profiles[sound]||profiles.balanced;const used=new Set(),lexicon=[];for(const meaning of CORE_MEANINGS){let term=makeWord(r,p);while(used.has(term))term=makeWord(r,p);used.add(term);lexicon.push({term,meaning,pronunciation:term.replace(/sh/g,'ʃ').replace(/th/g,'θ'),partOfSpeech:/^(I|you|we|they)$/.test(meaning)?'pronoun':/^(eat|drink|sleep|wake|go|come|see|hear|speak|know|think|want|give|take|make|break|fight|help|rule)$/.test(meaning)?'verb':/^(good|bad|big|small|old|new)$/.test(meaning)?'adjective':'noun'});}return {name,description:`Constructed language starter with ${wordOrder} word order and ${morphology} morphology.`,rules:{sounds:`Sound profile: ${sound}. Core vowels and consonant clusters are generated consistently from the language seed.`,phonotactics:'Words use one to three syllables, with optional final consonants. Extend this section with prohibited clusters and stress rules.',orthography:'Latin-script working orthography. Define alternate script, capitalization, punctuation, and transliteration here.',grammar:`Default word order: ${wordOrder}. Morphology: ${morphology}.`,morphology:`${morphology} morphology. Define case, agreement, derivation, plurality, possession, and verb marking here.`,syntax:`Primary clause order: ${wordOrder}. Record subordinate-clause, question, negation, relative-clause, and adjective placement rules here.`,tense:'Define tense, aspect, mood, evidentiality, and modality here.',pronouns:'Core pronouns are included in the generated lexicon. Add number, gender/class, formality, inclusive/exclusive, and case forms here.',numbers:'Define number words, base system, ordinals, fractions, and counting classifiers here.',names:'Use the same phonotactics for personal names unless a culture or historical layer uses a different system.',idioms:'Record metaphors, sayings, taboo terms, greetings, curses, and culture-specific expressions here.',dialects:'Record regional, class, historical, species, professional, or ceremonial varieties here.',writingSystem:'Define script direction, letter inventory, diacritics, ligatures, numerals, and handwriting conventions here.'},lexicon};},
    async browserEditorReview(text,instruction='Act as a careful developmental and line editor. Preserve voice, identify problems, explain why they matter, and suggest precise revisions without rewriting unnecessarily.'){
      const prompt=`${instruction}\n\nTEXT:\n${LF.stripHtml(text||'').slice(0,18000)}`;
      try{
        if(global.LanguageModel?.create){const session=await global.LanguageModel.create({temperature:.2,topK:3});const out=await session.prompt(prompt);session.destroy?.();return {mode:'browser-ai',text:out};}
        if(global.ai?.languageModel?.create){const session=await global.ai.languageModel.create({temperature:.2,topK:3});const out=await session.prompt(prompt);session.destroy?.();return {mode:'browser-ai',text:out};}
      }catch(_){ }
      const a=LF.writer.analyze(text);const notes=[];if(a.longSentences.length)notes.push(`${a.longSentences.length} long-sentence candidates may benefit from a rhythm or clarity pass.`);if(a.phrases.length)notes.push(`Common filler/weak-phrase candidates: ${a.phrases.slice(0,8).map(x=>`${x.phrase} (${x.count})`).join(', ')}.`);if(a.repeated.length)notes.push(`High-frequency content words: ${a.repeated.slice(0,8).map(x=>`${x.word} (${x.count})`).join(', ')}.`);if(a.passive.length)notes.push(`${a.passive.length} possible passive constructions are worth checking for intentionality.`);notes.push(`Readability: ${a.stats.flesch} (${LF.writer.readabilityLabel(a.stats.flesch)}), average sentence length ${a.stats.avgSentence} words, dialogue share about ${a.dialogueRatio}%.`);notes.push('Use Revision Lab and Continuity together: line-level polish should not erase characterization, world rules, setup/payoff, or chronology.');return {mode:'local-editor',text:notes.join('\n\n')};}
  };
})(window);
